name: ilmalogiya
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.5.3
  intl: any
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  loader_overlay: ^5.0.0
  freezed_annotation: ^3.1.0
  flutter_gen: ^5.12.0
  json_annotation: ^4.9.0
  keyboard_dismisser: ^3.0.0
  adaptive_theme: ^3.7.2
  http: ^1.6.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  photo_view: ^0.15.0
  photo_opener: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  build_runner: ^2.10.4
  freezed: ^3.2.3
  flutter_gen_runner: ^5.12.0
  json_serializable: ^6.11.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700


flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/logos/logo.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/logos/logo.png'

flutter_native_splash:
  color: "#f5e6cc"
  image: assets/logos/logo_banner_bigger.png
  color_dark: "#ffffff"
  image_dark: assets/logos/logo_banner_bigger.png

  android_12:
    image: assets/logos/logo_banner.png
    icon_background_color: "#f5e6cc"
    image_dark: assets/logos/logo_banner.png
    icon_background_color_dark: "#ffffff"

