name: ilmalogiya
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/logos/logo.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/logos/logo.png'

flutter_native_splash:
  color: "#f8eedb"
  image: assets/logos/logo_banner_bigger.png
  color_dark: "#f8eedb"
  image_dark: assets/logos/logo_banner_bigger.png

  android_12:
    image: assets/logos/logo_banner.png
    icon_background_color: "#f8eedb"
    image_dark: assets/logos/logo_banner.png
    icon_background_color_dark: "#f8eedb"

